In [34]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [45]:
!pip install pyucell -q
!pip install mygene -q
!pip install gseapy -q

Requirement already satisfied: pyucell in /usr/local/lib/python3.12/dist-packages (0.6.0)
Requirement already satisfied: anndata in /usr/local/lib/python3.12/dist-packages (from pyucell) (0.12.10)
Requirement already satisfied: joblib>=1.2 in /usr/local/lib/python3.12/dist-packages (from pyucell) (1.5.3)
Requirement already satisfied: numpy<2,>=1.23 in /usr/local/lib/python3.12/dist-packages (from pyucell) (1.26.4)
Requirement already satisfied: scanpy>=1.9 in /usr/local/lib/python3.12/dist-packages (from pyucell) (1.11.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from pyucell) (1.16.3)
Requirement already satisfied: session-info2 in /usr/local/lib/python3.12/dist-packages (from pyucell) (0.4)
Requirement already satisfied: h5py>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (3.16.0)
Requirement already satisfied: legacy-api-wrap>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (1.5)
Requirement already satisfied: matplotlib>=3.7.5 in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (3.10.0)
Requirement already satisfied: natsort in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (8.4.0)
Requirement already satisfied: networkx>=2.7.1 in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (3.6.1)
Requirement already satisfied: numba!=0.62.0rc1,>=0.57.1 in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (0.60.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (26.0)
Requirement already satisfied: pandas>=1.5.3 in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (2.2.2)
Requirement already satisfied: patsy!=1.0.0 in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (1.0.2)
Requirement already satisfied: pynndescent>=0.5.13 in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (0.6.0)
Requirement already satisfied: scikit-learn>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (1.6.1)
Requirement already satisfied: seaborn>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (0.13.2)
Requirement already satisfied: statsmodels>=0.14.5 in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (0.14.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (4.67.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (4.15.0)
Requirement already satisfied: umap-learn>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from scanpy>=1.9->pyucell) (0.5.11)
Requirement already satisfied: array-api-compat>=1.7.1 in /usr/local/lib/python3.12/dist-packages (from anndata->pyucell) (1.14.0)
Requirement already satisfied: zarr!=3.0.*,>=2.18.7 in /usr/local/lib/python3.12/dist-packages (from anndata->pyucell) (3.1.5)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.5->scanpy>=1.9->pyucell) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.5->scanpy>=1.9->pyucell) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.5->scanpy>=1.9->pyucell) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.5->scanpy>=1.9->pyucell) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.5->scanpy>=1.9->pyucell) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.5->scanpy>=1.9->pyucell) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.5->scanpy>=1.9->pyucell) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba!=0.62.0rc1,>=0.57.1->scanpy>=1.9->pyucell) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.3->scanpy>=1.9->pyucell) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.3->scanpy>=1.9->pyucell) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1.3->scanpy>=1.9->pyucell) (3.6.0)
Requirement already satisfied: donfig>=0.8 in /usr/local/lib/python3.12/dist-packages (from zarr!=3.0.*,>=2.18.7->anndata->pyucell) (0.8.1.post1)
Requirement already satisfied: google-crc32c>=1.5 in /usr/local/lib/python3.12/dist-packages (from zarr!=3.0.*,>=2.18.7->anndata->pyucell) (1.8.0)
Requirement already satisfied: numcodecs>=0.14 in /usr/local/lib/python3.12/dist-packages (from zarr!=3.0.*,>=2.18.7->anndata->pyucell) (0.16.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from donfig>=0.8->zarr!=3.0.*,>=2.18.7->anndata->pyucell) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.7.5->scanpy>=1.9->pyucell) (1.17.0)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 596.0/596.0 kB 10.2 MB/s eta 0:00:00

In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import mygene
import gseapy as gp

import pyucell as uc
import scanpy as sc

In [37]:
gene_degree = pd.read_csv('/content/drive/MyDrive/SSN/lioness_gene_degree_matrix.csv.gz', index_col=0)
print(gene_degree.shape)
print(gene_degree.head(3))
print(gene_degree.tail(3))

(18395, 517)

,CS0001,CS0005,CS0008,CS0009,CS0010,CS0019,CS0023,CS0046,CS0049,CS0050,...,I0341,I0521,I0467,I0125,I0525,I0338,I0524,I0251,I0276,I0221
ENSG00000000419,0,47,48,1,3,1,1,0,0,0,...,0,2,0,11,0,1,3,0,0,54
ENSG00000002746,2,0,279,0,5,3,1,0,1,2,...,1,0,0,2,1,46,0,0,53,0
ENSG00000001167,6,7,1,0,23,2,6,0,0,0,...,0,2,0,0,2,0,1,0,0,0
ENSG00000001630,7,85,0,0,0,0,33,0,2,33,...,35,9,8,1,0,0,0,0,3,2
ENSG00000001626,0,2,2,1,1,1,1,0,2,0,...,2,0,2,3,3,1,4,0,0,1

# Padronização

In [39]:
ids = gene_degree.index.tolist()

mg = mygene.MyGeneInfo()

result = mg.querymany(ids,
                      scopes='ensembl.gene',
                      fields='symbol',
                      species='human',
                      as_dataframe=True)

result.head(3)

WARNING:biothings.client:Input sequence provided is already in string format. No operation performed
WARNING:biothings.client:Input sequence provided is already in string format. No operation performed
INFO:biothings.client:querying 1-1000 ...
INFO:biothings.client:querying 1001-2000 ...
INFO:biothings.client:querying 2001-3000 ...
INFO:biothings.client:querying 3001-4000 ...
INFO:biothings.client:querying 4001-5000 ...
INFO:biothings.client:querying 5001-6000 ...
INFO:biothings.client:querying 6001-7000 ...
INFO:biothings.client:querying 7001-8000 ...
INFO:biothings.client:querying 8001-9000 ...
INFO:biothings.client:querying 9001-10000 ...
INFO:biothings.client:querying 10001-11000 ...
INFO:biothings.client:querying 11001-12000 ...
INFO:biothings.client:querying 12001-13000 ...
INFO:biothings.client:querying 13001-14000 ...
INFO:biothings.client:querying 14001-15000 ...
INFO:biothings.client:querying 15001-16000 ...
INFO:biothings.client:querying 16001-17000 ...
INFO:biothings.client:querying 17001-18000 ...
INFO:biothings.client:querying 18001-18395 ...
INFO:biothings.client:Finished.
WARNING:biothings.client:1 input query terms found dup hits:	[('ENSG00000175711', 2)]
WARNING:biothings.client:3 input query terms found no hit:	['ENSG00000148362', 'ENSG00000168078', 'ENSG00000189144']
INFO:biothings.client:Pass "returnall=True" to return complete lists of duplicate or missing query terms.

                   _id     _score symbol notfound
query
ENSG00000000419   8813  32.917847   DPM1      NaN
ENSG00000002746  23072  32.917847  HECW1      NaN
ENSG00000001167   4800  32.917847   NFYA      NaN

In [40]:
gene_degree['symbol'] = gene_degree.index.map(result['symbol'].to_dict())

gene_degree = gene_degree.dropna(subset='symbol')
gene_degree = gene_degree.drop_duplicates(subset='symbol')

gene_degree.set_index('symbol', inplace=True)
gene_degree.head()

,CS0001,CS0005,CS0008,CS0009,CS0010,CS0019,CS0023,CS0046,CS0049,CS0050,...,I0341,I0521,I0467,I0125,I0525,I0338,I0524,I0251,I0276,I0221
symbol,,,,,,,,,,,,,,,,,,,,,
DPM1,0,47,48,1,3,1,1,0,0,0,...,0,2,0,11,0,1,3,0,0,54
HECW1,2,0,279,0,5,3,1,0,1,2,...,1,0,0,2,1,46,0,0,53,0
NFYA,6,7,1,0,23,2,6,0,0,0,...,0,2,0,0,2,0,1,0,0,0
CYP51A1,7,85,0,0,0,0,33,0,2,33,...,35,9,8,1,0,0,0,0,3,2
CFTR,0,2,2,1,1,1,1,0,2,0,...,2,0,2,3,3,1,4,0,0,1

# Limpeza

In [41]:
print(gene_degree.shape)

# Caso exista qualquer valor diferente de zero, o gene é mantido
gene_degree = gene_degree.loc[ (gene_degree!=0).any(axis=1) ]
print(gene_degree.shape)

(18391, 517)
(18033, 517)

## Transformação para reduzir empates

In [43]:
gene_degree = np.log2(gene_degree + 1)

gene_degree.head(3)

,CS0001,CS0005,CS0008,CS0009,CS0010,CS0019,CS0023,CS0046,CS0049,CS0050,...,I0341,I0521,I0467,I0125,I0525,I0338,I0524,I0251,I0276,I0221
symbol,,,,,,,,,,,,,,,,,,,,,
DPM1,0.000000,5.584963,5.614710,1.0,2.000000,1.000000,1.000000,0.0,0.0,0.000000,...,0.0,1.584963,0.0,3.584963,0.000000,1.000000,2.0,0.0,0.000000,5.78136
HECW1,1.584963,0.000000,8.129283,0.0,2.584963,2.000000,1.000000,0.0,1.0,1.584963,...,1.0,0.000000,0.0,1.584963,1.000000,5.554589,0.0,0.0,5.754888,0.00000
NFYA,2.807355,3.000000,1.000000,0.0,4.584963,1.584963,2.807355,0.0,0.0,0.000000,...,0.0,1.584963,0.0,0.000000,1.584963,0.000000,1.0,0.0,0.000000,0.00000

Quanto maior o valor, maior o grau do gene indicado

# Procurando Gene Sets

In [50]:
gene_sets = gp.get_library(name='KEGG_2021_Human', organism='Human')
print(list(gene_sets.keys())[:3])

['ABC transporters', 'AGE-RAGE signaling pathway in diabetic complications', 'AMPK signaling pathway']